version: '3.8'

services:
  afi:
    build: .
    ports:
      - "8507:8507"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - AFI_PORT=8507
      - AFI_BACKEND_PORT=8508
      - AFI_INPUT_DIR=./data/Videos_Para_Editar
      - AFI_OUTPUT_DIR=./data/Videos_Agendados
      - AFI_MUSIC_DIR=./data/Musicas
      - AFI_LOG_DIR=./logs
    restart: unless-stopped
    
volumes:
  data:
  logs: